site_name: AIO Comcrawl
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Setup: setup.md
  - Usage: usage.md
  - Reference: reference.md
theme:
  name: material
  language: en
  palette:
    primary: deep purple
    accent: purple
  features:
    - navigation.instant
    - navigation.sections
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
